# Generated by Django 5.2.3 on 2025-07-09 16:15

import analises.models
import datetime
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseOleoDegomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(12, 15, 7, 359511), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('CR', 'Óleo Cru'), ('DG', 'Óleo Degomado'), ('RF', 'Óleo Refinado'), ('RS', 'Resíduo')], default='DG', max_length=2, verbose_name='Tipo de Amostra')),
                ('acidez', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acidez (mg KOH/g)')),
                ('umidade_oleo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Umidade do Óleo (%)')),
                ('impurezas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Impurezas (%)')),
                ('indice_iodo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Índice de Iodo (g I₂/100g)')),
                ('cor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cor (Lovibond)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Resultado da Análise (%)')),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Análise de Óleo Degomado',
                'verbose_name_plural': 'Análises de Óleo Degomado',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseProteina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(12, 15, 7, 359154), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica parada'), ('SA', 'Sem amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso da Amostra (g)')),
                ('ml_gasto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='mL Amostra')),
                ('ml_branco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do branco, entre 0 e 0.5', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='mL Branco')),
                ('normalidade', models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='O valor máximo de normalidade é 0.3 N.', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(Decimal('0.3'))], verbose_name='Normalidade do titulante (N)')),
                ('resultado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Resultado (%)')),
                ('resultado_corrigido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Resultado Corrigido (%)')),
                ('eh_media_24h', models.BooleanField(default=False, verbose_name='É média de 24h?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnaliseUmidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(12, 15, 7, 354129), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FG', 'Farelo Grosso'), ('FF', 'Farelo Fino'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado')], default='FG', max_length=2, verbose_name='Tipo de Amostra')),
                ('tara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Líquido')),
                ('peso_amostra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso da Amostra')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resultado')),
                ('fator_correcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Fator de Correção')),
            ],
            options={
                'verbose_name': 'Análise de Umidade',
                'verbose_name_plural': 'Análises de Umidade',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseUrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(12, 15, 7, 359859), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('amostra_1', models.DecimalField(decimal_places=2, help_text='Valor da primeira amostra', max_digits=10, verbose_name='Amostra 1')),
                ('amostra_2', models.DecimalField(decimal_places=2, help_text='Valor da segunda amostra', max_digits=10, verbose_name='Amostra 2')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado calculado automaticamente (Amostra 1 - Amostra 2)', max_digits=10, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Análise de Urase',
                'verbose_name_plural': 'Análises de Urase',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
