# Generated by Django 5.2.3 on 2025-07-14 15:25

import analises.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCinza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 751502), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_cadinho', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Cadinho (g)')),
                ('peso_cinza', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Cinza (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado (%)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Cinza',
                'verbose_name_plural': 'Análises de Cinza',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 752218), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_tara', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Tara (g)')),
                ('peso_fibra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Fibra (g)')),
                ('peso_branco', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Branco (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor de Fibra (%)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Fibra',
                'verbose_name_plural': 'Análises de Fibra',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseFosforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 752666), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('absorbancia_amostra', models.DecimalField(decimal_places=6, help_text='Digite apenas o valor da absorbância lida no equipamento', max_digits=8, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Absorbância da Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Peso da amostra em gramas (padrão: 1.0000g)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('concentracao_padrao', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), help_text='Concentração do padrão em mg/L (padrão: 10.0000)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Concentração Padrão (mg/L)')),
                ('volume_solucao', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Volume da solução em mL (padrão: 100.00)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume da Solução (mL)')),
                ('volume_aliquota', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Volume da alíquota em mL (padrão: 10.00)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume da Alíquota (mL)')),
                ('absorbancia_padrao', models.DecimalField(decimal_places=6, default=Decimal('0.250000'), help_text='Absorbância do padrão (padrão: 0.250000)', max_digits=8, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Absorbância do Padrão')),
                ('resultado', models.DecimalField(blank=True, decimal_places=3, help_text='Resultado calculado automaticamente usando a fórmula: (Aa × Cp × V × 1000 × 1000) / (P × VAl × Ap)', max_digits=10, null=True, verbose_name='Fósforo (ppm)')),
                ('casas_decimais', models.IntegerField(default=0, help_text='Número de casas decimais para exibir o resultado (0-6). 0 = número inteiro', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Casas Decimais')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Fósforo',
                'verbose_name_plural': 'Análises de Fósforo',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseOleoDegomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 750682), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('OP', 'Óleo Produção'), ('OE', 'Óleo Expedição')], default='OP', max_length=2, verbose_name='Tipo de Amostra')),
                ('tipo_analise', models.CharField(choices=[('UMI', 'Analise de Umidade'), ('ACI', 'Analise de Acidez'), ('SAB', 'Analise de Sabões')], default='UMI', max_length=3, verbose_name='Tipo de Analise')),
                ('tara', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tara')),
                ('liquido', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Líquido')),
                ('peso_amostra', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Peso da Amostra')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resultado')),
                ('titulacao', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Titulação')),
                ('fator_correcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Fator de Correção')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnaliseProteina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 750249), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica parada'), ('SA', 'Sem amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Peso da Amostra (g)')),
                ('ml_gasto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='mL Amostra')),
                ('ml_branco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor do branco, entre 0 e 0.5', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='mL Branco')),
                ('normalidade', models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='O valor máximo de normalidade é 0.3 N.', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(Decimal('0.3'))], verbose_name='Normalidade do titulante (N)')),
                ('resultado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Resultado (%)')),
                ('resultado_corrigido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Resultado Corrigido (%)')),
                ('eh_media_24h', models.BooleanField(default=False, verbose_name='É média de 24h?')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Proteína',
                'verbose_name_plural': 'Análises de Proteína',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseSilica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 753286), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('resultado_silica', models.DecimalField(decimal_places=2, help_text='Digite o resultado da análise de sílica', max_digits=5, verbose_name='Resultado Sílica (%)')),
                ('resultado_final', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado final: Cinza - Sílica (calculado automaticamente)', max_digits=5, null=True, verbose_name='Resultado Final (%)')),
                ('analise_cinza', models.ForeignKey(blank=True, help_text='Selecione a análise de cinza correspondente', null=True, on_delete=django.db.models.deletion.CASCADE, to='analises.analisecinza', verbose_name='Análise de Cinza')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Sílica',
                'verbose_name_plural': 'Análises de Sílica',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseTeorOleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 751850), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('LE', 'Lex'), ('CA', 'Casca'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=3, help_text='Entre 2,000 g e 2,500 g', max_digits=6, verbose_name='Peso da Amostra (g)')),
                ('peso_tara', models.DecimalField(decimal_places=3, help_text='Peso do recipiente vazio (antes da extração)', max_digits=6, verbose_name='Peso da Tara (g)')),
                ('peso_liquido', models.DecimalField(decimal_places=3, help_text='Peso do recipiente com óleo extraído (após extração)', max_digits=6, verbose_name='Peso Líquido (g)')),
                ('teor_oleo', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente: (Peso_liquido - Peso_tara) / Peso_amostra * 100', max_digits=5, null=True, verbose_name='Teor de Óleo (%)')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a análise', null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Teor de Óleo',
                'verbose_name_plural': 'Análises de Teor de Óleo',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseUmidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 746063), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FG', 'Farelo Grosso'), ('FF', 'Farelo Fino'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado')], default='FG', max_length=2, verbose_name='Tipo de Amostra')),
                ('tara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Líquido')),
                ('peso_amostra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso da Amostra')),
                ('resultado', models.DecimalField(blank=True, decimal_places=4, help_text='Calculado automaticamente: ((tara + peso_amostra) - liquido) / peso_amostra * 100', max_digits=10, null=True, verbose_name='Umidade (%)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Umidade',
                'verbose_name_plural': 'Análises de Umidade',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseUrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 25, 27, 751072), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('amostra_1', models.DecimalField(decimal_places=2, help_text='Valor da primeira amostra', max_digits=10, verbose_name='Amostra 1')),
                ('amostra_2', models.DecimalField(decimal_places=2, help_text='Valor da segunda amostra', max_digits=10, verbose_name='Amostra 2')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado calculado automaticamente (Amostra 1 - Amostra 2)', max_digits=10, null=True, verbose_name='Resultado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Análise de Urase',
                'verbose_name_plural': 'Análises de Urase',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
