# Generated by Django 5.2.3 on 2025-07-08 15:42

import analises.models
import datetime
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseOleoDegomado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 42, 17, 588190), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('OP', 'Óleo Produção'), ('OE', 'Óleo Expedição')], default='OP', max_length=2, verbose_name='Tipo de Amostra')),
                ('tipo_analise', models.CharField(choices=[('UMI', 'Analise de Umidade'), ('ACI', 'Analise de Acidez'), ('SAB', 'Analise de Sabões')], default='UMI', max_length=3, verbose_name='Tipo de Analise')),
                ('tara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Líquido')),
                ('peso_amostra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso da Amostra')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resultado')),
                ('titulacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Titulação')),
                ('fator_correcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Fator de Correção')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnaliseProteina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 42, 17, 587849), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Peso da Amostra (g)')),
                ('ml_gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='mL Amostra')),
                ('ml_branco', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Valor do branco, entre 0 e 0.5', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='mL Branco')),
                ('normalidade', models.DecimalField(decimal_places=5, default=0.1, help_text='Normalidade do titulante usada no cálculo (máx 1.00000)', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Normalidade do titulante (N)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado (%)')),
                ('resultado_corrigido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado Corrigido (%)')),
                ('eh_media_24h', models.BooleanField(default=False, verbose_name='É média de 24h?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnaliseUmidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 42, 17, 584447), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FG', 'Farelo Grosso'), ('FF', 'Farelo Fino'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado')], default='FG', max_length=2, verbose_name='Tipo de Amostra')),
                ('tara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Líquido')),
                ('peso_amostra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso da Amostra')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resultado')),
                ('fator_correcao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Fator de Correção')),
            ],
            options={
                'verbose_name': 'Análise de Umidade',
                'verbose_name_plural': 'Análises de Umidade',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseUrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 42, 17, 588525), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('amostra_1', models.DecimalField(decimal_places=2, help_text='Valor da primeira amostra', max_digits=10, verbose_name='Amostra 1')),
                ('amostra_2', models.DecimalField(decimal_places=2, help_text='Valor da segunda amostra', max_digits=10, verbose_name='Amostra 2')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado calculado automaticamente (Amostra 1 - Amostra 2)', max_digits=10, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Análise de Urase',
                'verbose_name_plural': 'Análises de Urase',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
