# Generated by Django 5.2.4 on 2025-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
    ]
