# Generated by Django 5.2.4 on 2025-07-11 06:17

import analises.models
import datetime
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCinza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(2, 17, 28, 375344), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_cadinho', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Cadinho (g)')),
                ('peso_cinza', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Cinza (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado (%)')),
            ],
            options={
                'verbose_name': 'Análise de Cinza',
                'verbose_name_plural': 'Análises de Cinza',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(2, 17, 28, 375962), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_tara', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Tara (g)')),
                ('peso_fibra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Fibra (g)')),
                ('peso_branco', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Branco (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor de Fibra (%)')),
            ],
            options={
                'verbose_name': 'Análise de Fibra',
                'verbose_name_plural': 'Análises de Fibra',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseFosforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(2, 17, 28, 376281), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('absorbancia_amostra', models.DecimalField(decimal_places=6, help_text='Digite apenas o valor da absorbância lida no equipamento', max_digits=8, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Absorbância da Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Peso da amostra em gramas (padrão: 1.0000g)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('concentracao_padrao', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), help_text='Concentração do padrão em mg/L (padrão: 10.0000)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Concentração Padrão (mg/L)')),
                ('volume_solucao', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Volume da solução em mL (padrão: 100.00)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume da Solução (mL)')),
                ('volume_aliquota', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Volume da alíquota em mL (padrão: 10.00)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume da Alíquota (mL)')),
                ('absorbancia_padrao', models.DecimalField(decimal_places=6, default=Decimal('0.250000'), help_text='Absorbância do padrão (padrão: 0.250000)', max_digits=8, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Absorbância do Padrão')),
                ('resultado', models.DecimalField(blank=True, decimal_places=3, help_text='Resultado calculado automaticamente usando a fórmula: (Aa × Cp × V × 1000 × 1000) / (P × VAl × Ap)', max_digits=10, null=True, verbose_name='Fósforo (ppm)')),
                ('casas_decimais', models.IntegerField(default=0, help_text='Número de casas decimais para exibir o resultado (0-6). 0 = número inteiro', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Casas Decimais')),
            ],
            options={
                'verbose_name': 'Análise de Fósforo',
                'verbose_name_plural': 'Análises de Fósforo',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseTeorOleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(2, 17, 28, 375655), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('LE', 'Lex'), ('CA', 'Casca'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=3, help_text='Entre 2,000 g e 2,500 g', max_digits=6, verbose_name='Peso da Amostra (g)')),
                ('peso_tara', models.DecimalField(decimal_places=3, help_text='Peso do recipiente vazio (antes da extração)', max_digits=6, verbose_name='Peso da Tara (g)')),
                ('peso_liquido', models.DecimalField(decimal_places=3, help_text='Peso do recipiente com óleo extraído (após extração)', max_digits=6, verbose_name='Peso Líquido (g)')),
                ('teor_oleo', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente: (Peso_liquido - Peso_tara) / Peso_amostra * 100', max_digits=5, null=True, verbose_name='Teor de Óleo (%)')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a análise', null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Análise de Teor de Óleo',
                'verbose_name_plural': 'Análises de Teor de Óleo',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(2, 17, 28, 374793), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(2, 17, 28, 374456), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(2, 17, 28, 369946), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(2, 17, 28, 375074), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='tipo_amostra',
            field=models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('PE', 'Peletizado'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra'),
        ),
    ]
