# Generated by Django 5.2.1 on 2025-07-07 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 17, 54, 243531), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 17, 54, 243092), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 17, 54, 242236), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 17, 54, 243919), verbose_name='Horário da Análise'),
        ),
    ]
