# Generated by Django 5.2.4 on 2025-07-06 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseurase',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='analiseurase',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(0, 5, 23, 445145), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(0, 5, 23, 444845), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(0, 5, 23, 441123), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(0, 5, 23, 445457), verbose_name='Horário da Análise'),
        ),
    ]
