# Generated by Django 5.2.3 on 2025-07-11 16:26

import analises.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_analisecinza_analisefibra_analisefosforo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecinza',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 559858), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefibra',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 560424), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefosforo',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 560668), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 559343), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 559029), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseteoroleo',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 560134), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 554800), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 26, 19, 559620), verbose_name='Horário da Análise'),
        ),
        migrations.CreateModel(
            name='AnaliseSilica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(12, 26, 19, 560963), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('resultado_silica', models.DecimalField(decimal_places=2, help_text='Digite o resultado da análise de sílica', max_digits=5, verbose_name='Resultado Sílica (%)')),
                ('resultado_final', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado final: Cinza - Sílica (calculado automaticamente)', max_digits=5, null=True, verbose_name='Resultado Final (%)')),
                ('analise_cinza', models.ForeignKey(blank=True, help_text='Selecione a análise de cinza correspondente', null=True, on_delete=django.db.models.deletion.CASCADE, to='analises.analisecinza', verbose_name='Análise de Cinza')),
            ],
            options={
                'verbose_name': 'Análise de Sílica',
                'verbose_name_plural': 'Análises de Sílica',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
