# Generated by Django 5.2.3 on 2025-07-09 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_analiseurase_atualizado_em_analiseurase_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 2, 44, 621918), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='peso_amostra',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Peso da Amostra'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 2, 44, 621606), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 2, 44, 620760), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 2, 44, 622227), verbose_name='Horário da Análise'),
        ),
    ]
