# Generated by Django 5.2.1 on 2025-05-20 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_alter_analiseproteina_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(21, 26, 20, 162925), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(21, 26, 20, 162225), verbose_name='Horário da Análise'),
        ),
    ]
