# Generated by Django 5.2.1 on 2025-07-07 21:22

import analises.models
import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_alter_analiseoleodegomado_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCinza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(17, 22, 37, 796576), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_cadinho', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Cadinho (g)')),
                ('peso_cinza', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Cinza (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado (%)')),
            ],
            options={
                'verbose_name': 'Análise de Cinza',
                'verbose_name_plural': 'Análises de Cinza',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(17, 22, 37, 796950), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_fibra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Fibra (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor de Fibra (%)')),
            ],
            options={
                'verbose_name': 'Análise de Fibra',
                'verbose_name_plural': 'Análises de Fibra',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseFosforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(17, 22, 37, 797122), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('volume_titulacao', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Volume de Titulação (mL)')),
                ('fator_correcao', models.DecimalField(decimal_places=4, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Fator de Correção')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor de Fósforo (%)')),
            ],
            options={
                'verbose_name': 'Análise de Fósforo',
                'verbose_name_plural': 'Análises de Fósforo',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseTeorOleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(17, 22, 37, 796769), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('SG', 'Soja em Grãos'), ('FL', 'Farelo')], default='SG', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_oleo', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Óleo Extraído (g)')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Teor de Óleo (%)')),
            ],
            options={
                'verbose_name': 'Análise de Teor de Óleo',
                'verbose_name_plural': 'Análises de Teor de Óleo',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 22, 37, 796155), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 22, 37, 795895), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 22, 37, 794653), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 22, 37, 796392), verbose_name='Horário da Análise'),
        ),
    ]
