# Generated by Django 5.2.3 on 2025-07-14 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_alter_analisecinza_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecinza',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 819445), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefibra',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 820281), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefosforo',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 820625), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 818793), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 818350), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisesilica',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 820995), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseteoroleo',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 819906), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 814029), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 11, 43, 819143), verbose_name='Horário da Análise'),
        ),
    ]
