# Generated by Django 5.2.4 on 2025-07-06 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_alter_analiseoleodegomado_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(18, 34, 22, 972949), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(18, 34, 22, 972688), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(18, 34, 22, 969474), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(18, 34, 22, 973255), verbose_name='Horário da Análise'),
        ),
    ]
