# Generated by Django 5.2.4 on 2025-07-07 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0003_analisecinza_analisefibra_analisefosforo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecinza',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 209913), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefibra',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 210248), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefosforo',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 210406), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 209509), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 209268), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseteoroleo',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 210084), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 208943), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(17, 26, 47, 209737), verbose_name='Horário da Análise'),
        ),
    ]
