# Generated by Django 5.2.1 on 2025-05-27 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0004_add_timestamp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 18, 48, 147792), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 18, 48, 147156), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorio',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='configuracaorelatorio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
