# Generated by Django 5.2.3 on 2025-07-08 16:46

import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0005_alter_analiseoleodegomado_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 46, 54, 818695), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 46, 54, 818337), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='ml_branco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do branco, entre 0 e 0.5', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)], verbose_name='mL Branco'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='normalidade',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='O valor máximo de normalidade é 0.3 N.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(Decimal('0.3'))], verbose_name='Normalidade do titulante (N)'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='peso_amostra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Peso da Amostra (g)'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='tipo_amostra',
            field=models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica parada'), ('SA', 'Sem amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 46, 54, 814865), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 46, 54, 818986), verbose_name='Horário da Análise'),
        ),
    ]
