# Generated by Django 5.2.4 on 2025-07-11 15:42

import analises.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0005_alter_analisecinza_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecinza',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 612342), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefibra',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 612912), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefosforo',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 613183), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 611766), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 611463), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseteoroleo',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 612626), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 607431), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 42, 38, 612064), verbose_name='Horário da Análise'),
        ),
        migrations.CreateModel(
            name='AnaliseSilica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('data', models.DateField(default=django.utils.timezone.localdate, validators=[analises.models.validate_not_future_date], verbose_name='Data da Análise')),
                ('horario', models.TimeField(default=datetime.time(11, 42, 38, 613529), verbose_name='Horário da Análise')),
                ('tipo_amostra', models.CharField(choices=[('FL', 'Farelo'), ('SI', 'Soja Industrializada'), ('FP', 'Fábrica Parada'), ('SA', 'Sem Amostra')], default='FL', max_length=2, verbose_name='Tipo de Amostra')),
                ('peso_amostra', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Amostra (g)')),
                ('peso_cadinho', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso do Cadinho (g)')),
                ('peso_silica', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Peso da Sílica (g)')),
                ('resultado_silica', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de sílica calculado automaticamente', max_digits=5, null=True, verbose_name='Resultado Sílica (%)')),
                ('resultado_final', models.DecimalField(blank=True, decimal_places=2, help_text='Resultado final: Cinza - Sílica (calculado automaticamente se análise de cinza estiver vinculada)', max_digits=5, null=True, verbose_name='Resultado Final (%)')),
                ('analise_cinza', models.ForeignKey(blank=True, help_text='Selecione a análise de cinza para calcular o resultado final', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analises.analisecinza', verbose_name='Análise de Cinza Relacionada')),
            ],
            options={
                'verbose_name': 'Análise de Sílica',
                'verbose_name_plural': 'Análises de Sílica',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
