# Generated by Django 5.2.1 on 2025-05-27 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0005_alter_analiseproteina_horario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoRelatorio',
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 19, 54, 552187), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 19, 54, 551655), verbose_name='Horário da Análise'),
        ),
    ]
