# Generated by Django 5.2.3 on 2025-07-08 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0006_alter_analiseoleodegomado_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 50, 42, 712470), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 50, 42, 712125), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 50, 42, 708748), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 50, 42, 712741), verbose_name='Horário da Análise'),
        ),
    ]
