# Generated by Django 5.2.4 on 2025-07-11 15:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0006_alter_analisecinza_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisesilica',
            name='peso_amostra',
        ),
        migrations.RemoveField(
            model_name='analisesilica',
            name='peso_cadinho',
        ),
        migrations.RemoveField(
            model_name='analisesilica',
            name='peso_silica',
        ),
        migrations.AlterField(
            model_name='analisecinza',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 87101), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefibra',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 87634), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisefosforo',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 87906), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 86521), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 86170), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisesilica',
            name='analise_cinza',
            field=models.ForeignKey(blank=True, help_text='Selecione a análise de cinza correspondente', null=True, on_delete=django.db.models.deletion.CASCADE, to='analises.analisecinza', verbose_name='Análise de Cinza'),
        ),
        migrations.AlterField(
            model_name='analisesilica',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 88203), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analisesilica',
            name='resultado_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Resultado final: Cinza - Sílica (calculado automaticamente)', max_digits=5, null=True, verbose_name='Resultado Final (%)'),
        ),
        migrations.AlterField(
            model_name='analisesilica',
            name='resultado_silica',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o resultado da análise de sílica', max_digits=5, verbose_name='Resultado Sílica (%)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analiseteoroleo',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 87347), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 82237), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseurase',
            name='horario',
            field=models.TimeField(default=datetime.time(11, 50, 44, 86831), verbose_name='Horário da Análise'),
        ),
    ]
