# Generated by Django 5.2 on 2025-05-29 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0006_delete_configuracaorelatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 37, 40, 336261), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(12, 37, 40, 332731), verbose_name='Horário da Análise'),
        ),
    ]
