# Generated by Django 5.2.3 on 2025-06-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0007_alter_analiseproteina_horario_and_more'),
        ('analises', '0007_analiseoleodegomado_alter_analiseproteina_horario_and_more'),
    ]

    operations = [
    ]
