# Generated by Django 5.2.1 on 2025-07-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0002_analiseurase_atualizado_em_analiseurase_criado_em_and_more'),
    ]

    operations = [
    ]
