# Generated by Django 5.2.3 on 2025-06-18 17:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0008_merge_20250618_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analiseoleodegomado',
            options={},
        ),
        migrations.RemoveField(
            model_name='analiseoleodegomado',
            name='acidez',
        ),
        migrations.RemoveField(
            model_name='analiseoleodegomado',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='analiseoleodegomado',
            name='impurezas',
        ),
        migrations.RemoveField(
            model_name='analiseoleodegomado',
            name='indice_iodo',
        ),
        migrations.RemoveField(
            model_name='analiseoleodegomado',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='analiseoleodegomado',
            name='umidade_oleo',
        ),
        migrations.AddField(
            model_name='analiseoleodegomado',
            name='fator_correcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Fator de Correção'),
        ),
        migrations.AddField(
            model_name='analiseoleodegomado',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Líquido'),
        ),
        migrations.AddField(
            model_name='analiseoleodegomado',
            name='peso_amostra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Peso da Amostra'),
        ),
        migrations.AddField(
            model_name='analiseoleodegomado',
            name='tara',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tara'),
        ),
        migrations.AddField(
            model_name='analiseoleodegomado',
            name='tipo_analise',
            field=models.CharField(choices=[('UMI', 'Analise de Umidade'), ('ACI', 'Analise de Acidez'), ('SAB', 'Analise de Sabões')], default='UMI', max_length=3, verbose_name='Tipo de Analise'),
        ),
        migrations.AddField(
            model_name='analiseoleodegomado',
            name='titulacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Titulação'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='horario',
            field=models.TimeField(default=datetime.time(13, 58, 26, 432630), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='analiseoleodegomado',
            name='tipo_amostra',
            field=models.CharField(choices=[('OP', 'Óleo Produção'), ('OE', 'Óleo Expedição')], default='OP', max_length=2, verbose_name='Tipo de Amostra'),
        ),
        migrations.AlterField(
            model_name='analiseproteina',
            name='horario',
            field=models.TimeField(default=datetime.time(13, 58, 26, 432435), verbose_name='Horário da Análise'),
        ),
        migrations.AlterField(
            model_name='analiseumidade',
            name='horario',
            field=models.TimeField(default=datetime.time(13, 58, 26, 431814), verbose_name='Horário da Análise'),
        ),
    ]
