# Generated by Django 5.2.4 on 2025-07-07 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0009_alter_analiseoleodegomado_horario_and_more'),
    ]

    operations = [
    ]
