# Generated by Django 5.2.1 on 2025-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_funcionario',
            field=models.CharField(blank=True, choices=[('analista', 'Analista'), ('producao', 'Produção'), ('classificacao-producao', 'Classificação - Produção')], max_length=30, null=True),
        ),
    ]
