# Generated by Django 5.2.4 on 2025-07-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_profile'),
        ('users', '0002_remove_profile_cpf_remove_profile_telefone'),
    ]

    operations = [
    ]
