# Generated by Django 5.2.1 on 2025-05-27 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Relatório')),
                ('tipo_relatorio', models.CharField(choices=[('UMIDADE', 'Relatório de Umidade'), ('PROTEINA', 'Relatório de Proteína'), ('COMBINADO', 'Relatório Combinado')], max_length=15, verbose_name='Tipo de Relatório')),
                ('periodo_padrao', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Período padrão em dias')),
                ('ativo', models.BooleanField(default=True, verbose_name='Relatório Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatórios',
                'ordering': ['nome'],
            },
        ),
    ]
