version: '3.8'

services:
  # Aplicação Django
  web:
    build:
      context: ../../..
      dockerfile: devops/docker/development/Dockerfile
    container_name: qualisoja-web-dev
    ports:
      - "8000:8000"
    volumes:
      - ../../..:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_volume:/app/db  # Volume para SQLite
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-change-me
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,0.0.0.0
    networks:
      - qualisoja-network
    restart: unless-stopped

  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: qualisoja-db-dev
    environment:
      POSTGRES_DB: qualisoja_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - qualisoja-network
    restart: unless-stopped

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: qualisoja-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - qualisoja-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Banco de dados admin (opcional)
  adminer:
    image: adminer:latest
    container_name: qualisoja-adminer-dev
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - qualisoja-network
    profiles:
      - tools

  # Redis admin (opcional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: qualisoja-redis-commander-dev
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - qualisoja-network
    profiles:
      - tools

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
  db_volume:
    driver: local

networks:
  qualisoja-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
