version: '3.8'

services:
  # Aplicação Django
  web:
    build:
      context: ../../..
      dockerfile: devops/docker/development/Dockerfile
    container_name: qualisoja-web-dev
    ports:
      - "8000:8000"
    volumes:
      - ../../..:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_volume:/app/db
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-change-me-qualisoja-2025
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,0.0.0.0
    networks:
      - qualisoja-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
  db_volume:
    driver: local

networks:
  qualisoja-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
