apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qualisoja.fullname" . }}-secret
  labels:
    {{- include "qualisoja.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.django.secretKey | b64enc | quote }}
  superuser-password: {{ .Values.django.superuser.password | b64enc | quote }}
